# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af57f2165d05bc59db5111bde89ea30d3535ad997a75278805f52bd571b9a72791f1299cb9d9b439ec29e4f9af4ab38ff1aacde99d9ce93b6cd0d953a193fd60

test:
  secret_key_base: 3d39b545467019cd9c4556db466ab2d8ce1d042cdb866315984da8d0a140de3d1080ca6d0e87c616a0e0fe50f8cc6ba67acbcc7762072616c2f329f3c634b4aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
